"use client";
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import {Orbit} from './editorial/orbit';
import {EditorialCursor} from './editorial/cursor';
import {HomeSections,Footer,About,PerspectivePage,ProjectsPage,ProjectDetail,Photography,Album,Blog,Article,Testimonials,Contact,Missing} from './editorial/pages';
const Admin=dynamic(()=>import('./admin/admin').then(m=>m.Admin));
const navigation=[['Início','/'],['Perfil','/sobre'],['Jornalismo','/jornalismo'],['Comunicação','/comunicacao'],['Fotografia','/fotografia'],['Textos','/blog'],['Depoimentos','/depoimentos'],['Contato','/contato']];
export function SiteShell(){const path=usePathname()||'/';const[open,setOpen]=useState(false);useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false)};addEventListener("keydown",close);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("reveal");observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll(".section").forEach(el=>observer.observe(el));return()=>{removeEventListener("keydown",close);observer.disconnect()}},[path]);const [section,slug]=path.slice(1).split('/');if(section==='admin')return <Admin/>;let content;if(!section)content=<><Orbit/><HomeSections/></>;else if(section==='sobre')content=<About/>;else if(section==='jornalismo'||section==='comunicacao')content=<PerspectivePage index={section==='jornalismo'?0:1}/>;else if(section==='projetos')content=slug?<ProjectDetail slug={slug}/>:<ProjectsPage/>;else if(section==='fotografia')content=slug?<Album slug={slug}/>:<Photography/>;else if(section==='blog')content=slug?<Article slug={slug}/>:<Blog/>;else if(section==='depoimentos')content=<Testimonials/>;else if(section==='contato')content=<Contact/>;else content=<Missing/>;return <><EditorialCursor/><a className="skip" href="#main">Ir para o conteúdo</a><aside className={'sidebar '+(open?'expanded':'')}><Link className="monogram" href="/" aria-label="Caroline Gonçalves — início">C<span>.</span></Link><button className="rail-toggle" aria-label="Expandir navegação" aria-expanded={open} onClick={()=>setOpen(!open)}>☰</button><nav aria-label="Navegação principal">{navigation.map(([label,url],i)=><Link className={path===url||url!=='/'&&path.startsWith(url)?'active':''} key={url} href={url} onClick={()=>setOpen(false)}><span>{String(i+1).padStart(2,'0')}</span><b>{label}</b></Link>)}</nav><div className="rail-social"><a href="https://www.instagram.com/ideiascomca/" aria-label="Instagram">Ig <b>Instagram ↗</b></a><a href="https://www.linkedin.com/in/comunicologacaroline/" aria-label="LinkedIn">In <b>LinkedIn ↗</b></a></div><span className="rail-bottom">© 2026</span></aside><header className="mobile-header"><Link href="/">C. <small>Caroline Gonçalves</small></Link><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Abrir menu">{open?'Fechar ×':'Menu +'}</button></header>{open&&<div className="mobile-menu"><nav>{navigation.map(([label,url],i)=><Link key={url} href={url} onClick={()=>setOpen(false)}><small>0{i+1}</small>{label}<span>↗</span></Link>)}</nav></div>}<main id="main" className="public-main" key={path}>{content}<Footer/></main></>}



