"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
const nav=[['01','Início','/'],['02','Sobre','/sobre'],['03','Projetos','/projetos'],['04','Fotografia','/fotografia'],['05','Blog','/blog'],['06','Depoimentos','/depoimentos'],['07','Contato','/contato']];
const projects=['Reportagem — placeholder','Comunicação — placeholder','Ensaio autoral — placeholder'];
const photos=['Retrato','Rua','Evento','Viagem','Editorial','Arquivo'];
export function SiteShell(){const[path,setPath]=useState('/');const[search,setSearch]=useState(false);const[photo,setPhoto]=useState<number|null>(null);useEffect(()=>{setPath(location.pathname);const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearch(true)}if(e.key==='Escape'){setSearch(false);setPhoto(null)}};addEventListener('keydown',f);return()=>removeEventListener('keydown',f)},[]);const p=path.split('/')[1]||'home';return <><header><Link className="brand" href="/">CAROLINE<br/>GONÇALVES</Link><nav>{nav.map(([n,l,h])=><Link key={h} href={h}><small>{n}</small>{l}</Link>)}</nav><button onClick={()=>setSearch(true)}>BUSCAR <small>CTRL K</small></button><Link className="cta" href="/contato">Vamos conversar</Link></header>{p==='home'&&<Home/>}{p==='sobre'&&<About/>}{p==='projetos'&&<Projects/>}{p==='fotografia'&&<Photography open={setPhoto}/>} {p==='blog'&&<Blog/>}{p==='depoimentos'&&<Testimonials/>}{(p==='contato'||p==='agendar')&&<Contact/>}{p==='admin'&&<Admin/>}{p==='privacidade'&&<Privacy/>}{!['home','sobre','projetos','fotografia','blog','depoimentos','contato','agendar','admin','privacidade'].includes(p)&&<NotFound/>}<Footer/>{search&&<div className="overlay"><section className="dialog"><button onClick={()=>setSearch(false)}>FECHAR ×</button><label>BUSCAR NO ARQUIVO<input autoFocus placeholder="Artigos, projetos, categorias..."/></label><p>CTRL K para abrir · ESC para fechar</p><Link href="/blog">ARTIGOS →</Link><Link href="/projetos">PROJETOS →</Link></section></div>}{photo!==null&&<div className="overlay"><section className="lightbox"><button onClick={()=>setPhoto(null)}>FECHAR ×</button><div className={'art p'+photo}/><div><small>ARQUIVO / 0{photo+1}</small><h2>{photos[photo]} / PLACEHOLDER</h2><p>Imagem reservada para substituição no CMS, com legenda, alt text, local e data.</p></div></section></div>}</>}
const Eye=({children}:{children:React.ReactNode})=><p className="eye">{children}</p>;
function Home(){return <main className="page home"><section><Eye>JORNALISMO / COMUNICAÇÃO / FOTOGRAFIA</Eye><h1>HISTÓRIAS<br/><i>MERECEM</i><br/>CONTEXTO.</h1><p className="lead">Jornalismo, comunicação e fotografia para contar histórias com informação, estratégia e sensibilidade.</p><div className="actions"><Link href="/projetos">Conheça meu trabalho →</Link><Link href="/contato">Vamos conversar →</Link></div></section><div className="hero art"><span>RETRATO PRINCIPAL<br/>A SUBSTITUIR</span></div><aside>BRASÍLIA — BR<br/><br/>ISSUE 01 / 2026<br/><br/>SCROLL ↓</aside></main>}
function About(){return <main className="page about"><section><Eye>02 / SOBRE</Eye><h1>QUEM É<br/><i>CAROLINE?</i></h1><p className="lead">Jornalista e pós-graduada em Marketing Estratégico Digital, com atuação entre reportagem, comunicação institucional e fotografia.</p><div className="tags">{['Jornalismo','Comunicação','Fotografia','Marketing digital','Conteúdo','SEO'].map(x=><span key={x}>{x}</span>)}</div></section><div className="portrait art"><span>RETRATO<br/>A SUBSTITUIR</span></div><section className="timeline"><Eye>MINHA TRAJETÓRIA</Eye><article><b>ATUAL</b><p>Repórter de Redes Sociais — Metrópoles</p></article><article><b>EXPERIÊNCIA</b><p>Comunicação, marketing, assessoria de imprensa e jornalismo.</p></article><small>Detalhes profissionais serão administrados por experiência.</small></section></main>}
function Projects(){return <main className="page"><Eye>03 / PORTFÓLIO</Eye><h1>PROJETOS<br/><i>SELECIONADOS.</i></h1><div className="cards">{projects.map((x,i)=><article key={x}><small>0{i+1} / PLACEHOLDER</small><div className={'art p'+i}/><h2>{x}</h2><p>Espaço editável para contexto, desafio e participação.</p><Link href="/contato">Abrir projeto →</Link></article>)}</div></main>}
function Photography({open}:{open:(n:number)=>void}){return <main className="page"><div className="photohead"><div><Eye>04 / ARQUIVO VISUAL</Eye><h1>FOTOGRAFIA</h1></div><p>Um arquivo de momentos, pessoas, lugares e histórias observadas através da minha lente.</p></div><div className="filters">Todos · Retratos · Eventos · Rua · Viagem</div><div className="gallery">{photos.map((x,i)=><button className={'art p'+i} key={x} onClick={()=>open(i)}><span>VIEW</span><small>{x} / placeholder</small></button>)}</div></main>}
function Blog(){return <main className="page"><Eye>05 / PUBLICAÇÃO</Eye><h1>CADERNO /<br/><i>ARTIGOS.</i></h1><article className="feature"><div className="art"/><section><Eye>EM DESTAQUE / PLACEHOLDER</Eye><h2>Uma história ainda<br/>em construção.</h2><p>Conteúdo demonstrativo, claramente identificado, pronto para receber artigos autorais.</p><Link href="/blog/artigo-placeholder">Ler artigo →</Link></section></article><div className="cards articles">{['História editorial — placeholder','Leitura de contexto — placeholder','Arquivo e observação — placeholder'].map((x,i)=><article key={x}><small>ARTIGO / 0{i+4} MIN</small><h2>{x}</h2><p>Lorem ipsum placeholder para conteúdo futuro.</p><Link href="/blog/artigo-placeholder">Ler →</Link></article>)}</div></main>}
function Testimonials(){return <main className="page quote"><Eye>06 / VOZES</Eye><p>01 / 10</p><blockquote>“Depoimento a ser inserido pela administração. A experiência de quem trabalhou com Caroline ganha aqui contexto e presença editorial.”</blockquote><p>NOME DO CONTATO<br/><small>CARGO / EMPRESA</small></p></main>}
function Contact(){const[sent,setSent]=useState(false);return <main className="page contact"><section><Eye>07 / CONTATO</Eye><h1>VAMOS<br/><i>CONVERSAR.</i></h1><p className="lead">Para pautas, projetos, coberturas e conversas que precisam de uma boa história.</p><div className="social">E-MAIL · WHATSAPP<br/>LINKEDIN · INSTAGRAM</div></section><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Nome<input required placeholder="Seu nome"/></label><label>Empresa<input placeholder="Onde você trabalha"/></label><label>E-mail<input required type="email" placeholder="voce@empresa.com"/></label><label>Assunto<select><option>Reportagem</option><option>Comunicação</option><option>Fotografia</option></select></label><label className="full">Mensagem<textarea required placeholder="Como posso ajudar?"/></label><button className="cta">Enviar mensagem →</button>{sent&&<p className="notice">Mensagem registrada. Obrigada pelo contato.</p>}</form></main>}
function Admin(){return <main className="page admin"><Eye>ADMINISTRAÇÃO / VISÃO GERAL</Eye><h1>Bom dia,<br/><i>Caroline.</i></h1><div className="stats">{[['00','Artigos publicados'],['03','Rascunhos'],['00','Fotografias'],['00','Mensagens']].map(([n,l])=><article key={l}><b>{n}</b><span>{l}</span></article>)}</div><div className="feature admincard"><section><Eye>ATIVIDADE RECENTE</Eye><p>Nenhuma publicação ainda. Comece pelo primeiro artigo ou fotografia.</p><button className="cta">Novo artigo →</button></section><section><Eye>ARQUIVO FOTOGRÁFICO</Eye><p>Seu arquivo fotográfico começa aqui.</p><button>Adicionar fotografia →</button></section></div></main>}
function Privacy(){return <main className="page text"><Eye>POLÍTICA DE PRIVACIDADE</Eye><h1>PRIVACIDADE<br/><i>EM CLAREZA.</i></h1><p>Estrutura inicial para a política de privacidade. Antes da publicação pública, dados de contato, análises e base legal precisam ser revisados.</p></main>};function NotFound(){return <main className="page text"><Eye>ERRO / 404</Eye><h1>ESSA PAUTA<br/>AINDA NÃO<br/><i>EXISTE.</i></h1><Link href="/">Voltar para a capa →</Link></main>};function Footer(){return <footer><b>CAROLINE<br/>GONÇALVES</b><span>JORNALISMO<br/>COMUNICAÇÃO<br/>FOTOGRAFIA</span><span>BRASÍLIA — BRASIL<br/>© 2026 CAROLINE GONÇALVES</span></footer>}
