"use client";
import {EditorialImage} from './image';
import Link from 'next/link';
import {motion,useReducedMotion} from 'motion/react';
import {useState} from 'react';
import {perspectives,portrait} from '@/data/content';
export function Orbit(){const reduced=useReducedMotion();const [selected,setSelected]=useState<number|null>(null);return <section className={'orbit '+(selected!==null?'is-selected':'')} aria-label="Explore as três perspectivas"><div className="hero-top"><span>CAROLINE GONÇALVES / JORNALISTA</span><span>BRASÍLIA, BRASIL — 2026</span></div><div className="orbit-stage"><div className="orbit-guide"/><motion.div className="portrait-frame" animate={{scale:selected===null?1:.92,rotate:selected===null?-3:2}} transition={{duration:reduced?0:.65}}><EditorialImage src={portrait} alt="Caroline Gonçalves fotografando com sua câmera" fetchPriority="high"/><span className="image-note">UM OLHAR. DIFERENTES PERSPECTIVAS.</span></motion.div><h1 className="hero-name">Caroline<br/><em>Gonçalves.</em></h1>{perspectives.map((p,i)=>{const slot=selected===null?i:(i-selected+3)%3;return <motion.button key={p.route} className={'axis axis-'+slot+(selected===i?' chosen':'')} onClick={()=>setSelected(selected===i?null:i)} aria-expanded={selected===i} layout transition={{duration:reduced?0:.7,ease:[.65,0,.25,1]}} animate={{opacity:selected===null||selected===i?1:.68,scale:selected===null||selected===i?1:.88}}><span className="axis-number">0{i+1}<span className="axis-dot"/></span><strong>{p.name}</strong><small>{p.subtitle}</small><span className="axis-arrow">↗</span></motion.button>})}{selected!==null&&<motion.div key={selected} className="orbit-details" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:reduced?0:.25,duration:reduced?0:.5}}><span className="eyebrow">PERSPECTIVA 0{selected+1}</span><div>{perspectives[selected].areas.map(a=><span key={a}>{a}</span>)}</div><Link className="text-link" href={perspectives[selected].route}>EXPLORAR {perspectives[selected].name.toUpperCase()} <span>→</span></Link></motion.div>}</div><section className="hero-manifesto"><span className="eyebrow">UM TRABALHO, TRÊS LINGUAGENS</span><h2 className="manifesto">Palavras <em>informam.</em><br/>Estratégia <em>aproxima.</em><br/>Imagens <em>permanecem.</em></h2></section><div className="mobile-perspectives">{perspectives.map((p,i)=><div key={p.route}><button onClick={()=>setSelected(selected===i?null:i)} aria-expanded={selected===i}><span>0{i+1}</span>{p.name} <span>↗</span></button>{selected===i&&<div className="mobile-details"><p>{p.areas.join(' · ')}</p><Link href={p.route}>EXPLORAR {p.name.toUpperCase()} →</Link></div>}</div>)}</div></section>}



